[package]
name = "raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.28"
rayon = "1.10"
mint = "0.5"
ultraviolet = { version = "0.9", features = ["mint", "int", "f64"] }

palette = { version = "0.7", features = ["wide"] }

# todo also optimize and use https://docs.rs/simba/0.9.0/simba/

wide = "0.7"
itertools = "0.14"

incr_stats = { version = "1.0", optional = true }

[features]
default = []
simd_render = []
simulate_slow_render = []
render_timing_debug = ["incr_stats"]
high_resolution = []
