[package]
name = "raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.28"
rayon = "1.10"
mint = "0.5"
ultraviolet = { version = "0.9", features = ["mint", "int"] }
color = "0.2"
wide = "0.7"
itertools = "0.14"

[features]
simd_render = []
simulate_slow_render = []
high_resolution = []
